server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gobang?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    #    username: root
    #    password: 123456
    driverClassName: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lxw.golang.entity
#lxw:
#  redis:
#    cache:
#      addr: 127.0.0.1
#      port: 6379
#      password: c6z0RuONsPB06gE8
#      maxActive: 1024
#      maxIdle: 200
#      maxWait: 10000
#      timeout: 10000
#      testOnBorrow: true
